"""initial schema

Revision ID: 203a8d0115e8
Revises: 
Create Date: 2026-09-17 19:58:26.316162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '203a8d0115e8'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('code', sa.String(length=32), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_code'), ['code'], unique=True)

    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_role'), ['role'], unique=False)

    op.create_table('credential',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.String(length=64), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('issued_by_user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('programme', sa.String(length=255), nullable=False),
    sa.Column('issue_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('document_sha256', sa.String(length=64), nullable=False),
    sa.Column('storage_key', sa.String(length=255), nullable=False),
    sa.Column('original_filename', sa.String(length=255), nullable=False),
    sa.Column('document_available', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['issued_by_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('storage_key')
    )
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_credential_credential_id'), ['credential_id'], unique=True)
        batch_op.create_index(batch_op.f('ix_credential_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_credential_status'))
        batch_op.drop_index(batch_op.f('ix_credential_credential_id'))

    op.drop_table('credential')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_role'))
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    with op.batch_alter_table('institution', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_code'))

    op.drop_table('institution')
    # ### end Alembic commands ###
