"""add credential lifecycle and integrity models

Revision ID: 55970b0b7a9f
Revises: 679f5e2da96e
Create Date: 2026-09-17 20:36:25.778098

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55970b0b7a9f'
down_revision = '679f5e2da96e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('integrity_check',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('credential_id', sa.Integer(), nullable=False),
    sa.Column('checked_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('current_sha256', sa.String(length=64), nullable=True),
    sa.Column('result', sa.String(length=20), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.ForeignKeyConstraint(['credential_id'], ['credential.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('integrity_check', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_integrity_check_credential_id'), ['credential_id'], unique=False)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('expiry_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_column('expiry_date')
        batch_op.drop_column('description')

    with op.batch_alter_table('integrity_check', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_integrity_check_credential_id'))

    op.drop_table('integrity_check')
    # ### end Alembic commands ###
