"""add tamper evident audit hashes

Revision ID: 7e0101b4a656
Revises: f3e0dcf0da7d
Create Date: 2026-09-25 13:10:00.123424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7e0101b4a656'
down_revision = 'f3e0dcf0da7d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('previous_event_hash', sa.String(length=64), nullable=True))
        batch_op.add_column(sa.Column('event_hash', sa.String(length=64), nullable=False))
        batch_op.create_unique_constraint('uq_audit_event_event_hash', ['event_hash'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('audit_event', schema=None) as batch_op:
        batch_op.drop_constraint('uq_audit_event_event_hash', type_='unique')
        batch_op.drop_column('event_hash')
        batch_op.drop_column('previous_event_hash')

    # ### end Alembic commands ###
