"""add student vault and university verification foundation

Revision ID: 8a1b15bca694
Revises: 7e0101b4a656
Create Date: 2026-09-25 13:22:44.396224

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8a1b15bca694'
down_revision = '7e0101b4a656'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('institution_verification_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('representative_user_id', sa.Integer(), nullable=False),
    sa.Column('official_email_domain', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reviewer_user_id', sa.Integer(), nullable=True),
    sa.Column('review_note', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['representative_user_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['reviewer_user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id')
    )
    with op.batch_alter_table('institution_verification_request', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_institution_verification_request_status'), ['status'], unique=False)

    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('message', sa.String(length=500), nullable=False),
    sa.Column('is_read', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_notification_user_id'), ['user_id'], unique=False)

    op.create_table('student_profile',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('institution_id', sa.Integer(), nullable=False),
    sa.Column('student_identifier', sa.String(length=100), nullable=False),
    sa.ForeignKeyConstraint(['institution_id'], ['institution.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('institution_id', 'student_identifier', name='uq_student_identifier_per_institution')
    )
    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_student_profile_institution_id'), ['institution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profile_student_identifier'), ['student_identifier'], unique=False)
        batch_op.create_index(batch_op.f('ix_student_profile_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.add_column(sa.Column('student_profile_id', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_credential_student_profile_id'), ['student_profile_id'], unique=False)
        batch_op.create_foreign_key('fk_credential_student_profile', 'student_profile', ['student_profile_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('credential', schema=None) as batch_op:
        batch_op.drop_constraint('fk_credential_student_profile', type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_credential_student_profile_id'))
        batch_op.drop_column('student_profile_id')

    with op.batch_alter_table('student_profile', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_student_profile_user_id'))
        batch_op.drop_index(batch_op.f('ix_student_profile_student_identifier'))
        batch_op.drop_index(batch_op.f('ix_student_profile_institution_id'))

    op.drop_table('student_profile')
    with op.batch_alter_table('notification', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_notification_user_id'))

    op.drop_table('notification')
    with op.batch_alter_table('institution_verification_request', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_institution_verification_request_status'))

    op.drop_table('institution_verification_request')
    # ### end Alembic commands ###
